### ISSUE TITLE
User can "upload" on user profiles

### ISSUE THREAD

**Issue by ghost** [SychO9/flarum-profile-cover#10]
Hello, users are able to upload on other users profiles. You cant upload but it shows that you can.

I would appreciate a fix :)

**Comment by SychO9** [comment]
thanks for the report, I'll look into it as soon as possible

**Comment by SychO9** [comment]
Fixed in https://github.com/SychO9/flarum-profile-cover/commit/213f303ac17e15d4b569e8f904bf05009fda80c3
