### ISSUE TITLE
Compatibility with flarum 0.1-beta11

### ISSUE THREAD

**Issue by maicol07** [SychO9/flarum-profile-cover#11]
Please add compatibility with latest Flarum version.
Specs: https://flarum.org/docs/extend/start.html#extension-packaging

**Comment by SychO9** [comment]
Although no changes appear to be needed to make the package compatible with beta 11,
the version constraint for flarum has been updated here https://github.com/SychO9/flarum-profile-cover/commit/6c2e8d2db137f78a044cd21880294ef6bad6633d
