### ISSUE TITLE
Extension breaks admin panel

### ISSUE THREAD

**Issue by maicol07** [SychO9/flarum-profile-cover#2]
Hi,
this extension breaks admin panel. Can you fix it?
Also, increase upload limit (2 MB is really a low limit)
Thanks

**Comment by SychO9** [comment]
Can you please give me more details ? how does it break the admin panel exactly ?
any error messages ?
screenshots ?

**Comment by maicol07** [comment]
Oh yeah. Here it is a screenshot:
![immagine](https://user-images.githubusercontent.com/9463142/66717289-8ebccc00-edd7-11e9-8773-e8e4c8d8ebe4.png)
It shows that message on every admin page

**Comment by SychO9** [comment]
check the browser console please and paste the error you are getting

**Comment by maicol07** [comment]
Here you go:
![immagine](https://user-images.githubusercontent.com/9463142/66717309-f07d3600-edd7-11e9-853e-10e5ea781550.png)

**Comment by SychO9** [comment]
It should be fixed in version 0.1.2 but I can't tell for sure, if you do try it please let me know,
as for the size limit, I plan to give the admin the ability to choose the limit instead of it being hard-coded, so I'll leave that for the next version.

And thank you for the report!
